import pandas as pd

# ---------------------------------------------------------
# Column description helpers
# ---------------------------------------------------------

def build_common_docs() -> dict:
    # Base descriptions reused across datasets
    return {
        "index": "Row index within this file (0-based).",
        "match_id": "Identifier of the match.",
        "frame_start": "First tracking frame index associated with this row.",
        "frame_end": "Last tracking frame index associated with this row.",
        "frame_physical_start": "First frame index within the physical (on-pitch) action.",
        "time_start": "Start time of this row (hh:mm.ss within the match period).",
        "time_end": "End time of this row (hh:mm.ss within the match period).",
        "minute_start": "Start minute (integer) of this row.",
        "second_start": "Start second (integer) of this row.",
        "duration": "Duration of this row in seconds (approx).",
        "period": "Match period (1 = first half, 2 = second half, etc.).",
        "attacking_side_id": "Numeric code for the side currently attacking.",
        "attacking_side": "Text label for the side currently attacking (home / away).",
        "team_id": "Identifier of the team related to this row.",
        "team_shortname": "Short name / acronym of the team.",
        "x_start": "Start x-coordinate of the event/phase (pitch length axis, in metres).",
        "y_start": "Start y-coordinate of the event/phase (pitch width axis, in metres).",
        "x_end": "End x-coordinate of the event/phase.",
        "y_end": "End y-coordinate of the event/phase.",
        "channel_start": "Pitch vertical ‘channel’ at the start location (e.g. left / half-space / central).",
        "channel_end": "Pitch vertical ‘channel’ at the end location.",
        "third_start": "Pitch third at the start location (defensive / middle / attacking).",
        "third_end": "Pitch third at the end location.",
        "penalty_area_start": "Whether the start location is inside the penalty area.",
        "penalty_area_end": "Whether the end location is inside the penalty area.",
        "lead_to_shot": "Flag indicating that this row is in the build-up to a shot.",
        "lead_to_goal": "Flag indicating that this row is in the build-up to a goal.",
    }





def build_phases_docs(df: pd.DataFrame) -> pd.DataFrame:
    docs = build_common_docs()
    docs.update(
        {
            "team_in_possession_id": "Team identifier for the team in possession throughout the phase.",
            "team_in_possession_shortname": "Short name of the team in possession during the phase.",
            "n_player_possessions_in_phase": "Number of individual on-ball player possessions within this phase.",
            "phase_type_id": "Numeric code describing the phase type (e.g. build-up, sustained attack).",
            "phase_type": "Text label for the phase type.",
            "team_in_possession_width_start": "Width of the team in possession at the start of the phase.",
            "team_in_possession_width_end": "Width of the team in possession at the end of the phase.",
            "team_in_possession_length_start": "Length of the team in possession at the start of the phase.",
            "team_in_possession_length_end": "Length of the team in possession at the end of the phase.",
            "team_out_of_possession_width_start": "Width of the out-of-possession team at the start of the phase.",
            "team_out_of_possession_width_end": "Width of the out-of-possession team at the end of the phase.",
            "team_out_of_possession_length_start": "Length of the out-of-possession team at the start of the phase.",
            "team_out_of_possession_length_end": "Length of the out-of-possession team at the end of the phase.",
            "team_possession_loss_in_phase": "Does the team lose possession at the end of this phase",
            "team_possession_lead_to_goal": "Does the team in possession lead to a goal in this phase",
            "team_possession_lead_to_shot": "Does the team in possession lead to a shot in this phase",
            "team_in_possession_phase_type": "Phase type label for the team in possession",
            "team_in_possession_phase_type_id": "Phase type ID for the team in possession",
            "team_out_of_possession_phase_type": "Phase type label for the team out of possession",
            "team_out_of_possession_phase_type_id": "0 (build_up) / 1 (create) / 2 (finish) / 3 (quick_break) / 4 (transition) / 5 (chaotic) / 6 (direct) / 7 (set_play) ",
            "channel_id_start": "Channel id where the event starts. 1 (wide_left) / 2 (half_space_left) / 3 (center) / 4 (half_space_right) / 5 (wide_right) ",
            "channel_id_end": "Channel id where the event ends. 1 (wide_left) / 2 (half_space_left) / 3 (center) / 4 (half_space_right) / 5 (wide_right) ",
            "third_id_end": "Third id where the event ends. 1 (defensive_third)) / 2 (middle_third) / 3 (attacking_third) ",
        }
    )

    rows = []
    for col in df.columns:
        desc = docs.get(col, "No description added yet – refer to SkillCorner documentation if needed.")
        rows.append({"column": col, "description": desc})

    return pd.DataFrame(rows)


def build_tracking_docs(df: pd.DataFrame) -> pd.DataFrame:
    docs = {
        "frame": "Sequential index of the tracking frame.",
        "timestamp": "Time within the match period (hh:mm:ss.ff) for this frame.",
        "period": "Match period (1 = first half, 2 = second half, etc.).",
        "ball_x": "Ball x-coordinate in pitch metres (length).",
        "ball_y": "Ball y-coordinate in pitch metres (width).",
        "ball_z": "Ball z-coordinate in metres (height).",
        "ball_is_detected": "True if the ball is detected in this frame, False otherwise.",
        "in_possession_player_id": "Identifier of the player considered in possession for this frame.",
        "in_possession_group": "Group label for possession (home / away / none).",
        "n_players": "Number of players with tracking data in this frame.",
        }

    rows = []
    for col in df.columns:
        desc = docs.get(col, "No description added yet – derived from tracking_extrapolated.jsonl.")
        rows.append({"column": col, "description": desc})

    return pd.DataFrame(rows)

def build_dynamic_events_docs(df: pd.DataFrame) -> pd.DataFrame:
    docs = build_common_docs()
    docs.update(
        {
            "event_id": "Unique identifier of the event (string key).",
            "event_type_id": "Numeric code for the event type.",
            "event_type": "Event type (e.g. pass, carry, duel, shot).",
            "player_id": "Identifier of the main player involved in the event.",
            "player_shortname": "Short name of the player linked to the event.",
            "player_in_possession_id": "Identifier of the player in possession at this moment.",
            "player_in_possession_shortname": "Short name of the player in possession.",
            "player_in_possession_position": "On-pitch position label for the player in possession.",
            "team_in_possession_id": "Team identifier for the team in possession.",
            "team_in_possession_shortname": "Short name of the team in possession.",
            "game_interruption_before": "Type of interruption immediately before this event (kick-off, foul, etc.).",
            "game_interruption_after": "Type of interruption immediately after this event.",
            "xg": "Expected Goals (if present) – model estimate of scoring probability for this event.",
            "xa": "Expected Assists (if present) – contribution to shot creation.",
            "xloss_player_possession_end": "SkillCorner metric of possession value loss/gain by the player at the end of the event.",
            "team_in_possession_width_start": "Width (max y - min y) of the team in possession at event start.",
            "team_in_possession_length_start": "Length (max x - min x) of the team in possession at event start.",
            "team_out_of_possession_width_start": "Width of the out-of-possession team at event start.",
            "team_out_of_possession_length_start": "Length of the out-of-possession team at event start.",
            "event_subtype_id": "Numeric code for the event subtype. 1 (behind) / 2 (coming_short) / 3 (cross_receiver) / 4 (dropping_off) / 5 (overlap) / 6 (pulling_half_space) / 7 (pulling_wide) / 8 (run_ahead_of_the_ball) / 9 (support) / 10 (underlap) / 11 (pressing) / 12 (pressure) / 13 (counter_press) / 14 (recovery_press) / 15 (other)",
            "event_subtype": "Subtype of the event.  None for Player Possessions and Passing Options.",
            "player_name": "Name of the player performing the event.",
            "player_position_id": "1(GK),2(LB),3(LWB),4(LCB),5(CB),6( RCB),7(RWB),8(RB),9(LDM),10(DM), 11(RDM),12(LM),13(CM),14(RM),15( AM),16(LW),17(RW),18(LF),19(CF),20 (RF)",
            "player_position": "Position of the player.",
            "player_in_possession_name": "Name of the player in possession.",
            "player_in_possession_position_id": "Position ID of the player in possession.",
            "channel_id_start": "Channel id where the event starts. 1 (wide_left) / 2 (half_space_left) / 3 (center) / 4 (half_space_right) / 5 (wide_right) ",
            "channel_id_end": "Channel id where the event ends. 1 (wide_left) / 2 (half_space_left) / 3 (center) / 4 (half_space_right) / 5 (wide_right) ",
            "third_id_start": "Third id where the event starts. 1 (defensive_third)) / 2 (middle_third) / 3 (attacking_third) ",
            "third_id_end": "Third id where the event ends. 1 (defensive_third)) / 2 (middle_third) / 3 (attacking_third) ",
            "associated_player_possession_event_id": "ID of the associated player possession event.",
            "associated_player_possession_frame_start": "Start frame of the associated player possession.",
            "associated_player_possession_frame_end": "End frame of the associated player possession.",
            "associated_player_possession_end_type_id": "End type ID of the associated player possession.",
            "associated_player_possession_end_type": "End type of the associated player possession.",
            "associated_off_ball_run_event_id": "ID of the associated off-ball run event.",
            "associated_off_ball_run_subtype_id": "Subtype ID of the associated off-ball run event.",
            "associated_off_ball_run_subtype": "Subtype of the associated off-ball run event.",
            "game_state_id": "ID representing the current game state.",
            "game_state": "Description of the current game state.",
            "team_score": "Score of the team in possession.",
            "opponent_team_score": "Score of the opposing team.",
            "phase_index": "Index of the current phase.",
            "player_possession_phase_index": "Index of the player possession phase.",
            "first_player_possession_in_team_possession": "Indicates if this is the first player possession in the team possession.",
            "last_player_possession_in_team_possession": "Indicates if this is the last player possession in the team possession.",
            "lead_to_different_phase": "Indicates if the event leads to a different phase.",
            "issued_from_different_phase": "Indicates if the event is issued from a different phase.",
            "n_player_possessions_in_phase": "Number of player possessions in the phase.",
            "team_possession_loss_in_phase": "Indicates if there was a team possession loss in the phase.",
            "team_in_possession_phase_type_id": "Phase type ID for the team in possession.",
            "team_in_possession_phase_type": "Phase type label for the team in possession",
            "team_out_of_possession_phase_type_id": "Phase type ID for the team out of possession.",
            "team_out_of_possession_phase_type": "Phase type label for the team out of possession.",
            "current_team_in_possession_next_phase_type_id": "Next phase type ID for the team in possession.",
            "current_team_in_possession_next_phase_type": "Next phase type label for the team in possession.",
            "current_team_out_of_possession_next_phase_type_id": "Next phase type ID for the team out of possession.",
            "current_team_out_of_possession_next_phase_type": "Next phase type label for the team out of possession.",
            "current_team_in_possession_previous_phase_type_id": "Previous phase type ID for the team in possession.",
            "current_team_in_possession_previous_phase_type": "Previous phase type label for the team in possession.",
            "current_team_out_of_possession_previous_phase_type_id": "Previous phase type ID for the team out of possession.",
            "current_team_out_of_possession_previous_phase_type": "Previous phase type label for the team out of possession.",
            "game_interruption_before_id": "ID of the game interruption before the phase.",
            "distance_covered": "On-ball Engagements: Distance covered (in metres) by the player between when the player starts his physical effort (frame_physical_start) and when the event ends (frame_end).  Other Event Types: Distance covered (in metres) by the player during the event (between frame_start and frame_end).  It is based on the actual player's trajectory.",
            "trajectory_angle": "On-ball Engagements Distance covered (in metres) by the player between when the player starts his physical effort (frame_physical_start) and when the event ends (frame_end).  Other Event Types Distance covered (in metres) by the player during the event (between frame_start and frame_end).  It is based on the actual player's trajectory.",
            "trajectory_direction_id": "1 (forward) / 2 (backward) / 3 (sideway left) / 4 (sideway right)",
            "trajectory_direction": "Direction of the player trajectory.",
            "in_to_out": "None if the player did not cover at least 2m during the event.  TRUE if the player the player - moved sideway (here we use trajectory_angle absolute value is between 22.5° and 157°). - started from the center channel and ends in the half space or wide channel OR started in the half space and ends in the wide channel  Else FALSE. ",
            "out_to_in": "None if the player did not cover at least 2m during the event.  TRUE if the player the player - moved sideway (here we use trajectory_angle absolute value is between 22.5° and 157°). - started from the wide channel and ends in the center or a half space channel OR started in the half space and ends in the central channel  Else FALSE. ",
            "speed_avg": "The average speed of a player during the event (km/h) when he is detected on screen.  None if there are not enough data points to compute the average or if the value is not considered trustworthy enough. On-ball engagements Computed between the frame_physical_start and frame_end.  Other event types Computed between the frame_start and frame_end.",
            "speed_avg_band_id": "None / 1 (jogging) / 2 (running) / 3 (hsr) / 4 (sprinting) ",
            "speed_avg_band": "Speed band of the average speed.  None if speed_avg cannot be delivered.",
            "separation_start": "Separation at the start of the event.",
            "separation_end": "Separation at the end of the event.",
            "separation_gain": "Gain in separation during the event.",
            "last_defensive_line_x_start": "X-coordinate of the last defensive line at the start of the event.",
            "last_defensive_line_x_end": "X-coordinate of the last defensive line at the end of the event.",
            "delta_to_last_defensive_line_start": "Change in distance to the last defensive line at the start of the event.",
            "delta_to_last_defensive_line_end": "Change in distance to the last defensive line at the end of the event.",
            "delta_to_last_defensive_line_gain": "Gain in change in distance to the last defensive line during the event.",
            "last_defensive_line_height_start": "Height of the last defensive line at the start of the event.",
            "last_defensive_line_height_end": "Height of the last defensive line at the end of the event.",
            "last_defensive_line_height_gain": "Gain in height of the last defensive line during the event.",
            "inside_defensive_shape_start": "Whether the player was inside the defensive shape at the start of the event.",
            "inside_defensive_shape_end": "Whether the player was inside the defensive shape at the end of the event.",
            "start_type_id": "Identifier for the type of start of the event.",
            "start_type": "Description of the type of start of the event.",
            "end_type_id": "Identifier for the type of end of the event.",
            "end_type": "Description of the type of end of the event.",
            "consecutive_on_ball_engagements": "Number of consecutive on-ball engagements.",
            "one_touch": "Whether the event was a one-touch action.",
            "quick_pass": "Whether the event was a quick pass.",
            "carry": "Whether the event was a carry.",
            "forward_momentum": "TRUE if the forward momentum conditions are respected. Else FALSE.",
            "is_header": "TRUE if the possession was a header. Else FALSE.",
            "hand_pass": "Whether the event was a hand pass.",
            "initiate_give_and_go": "Whether the event initiated a give and go.",
            "pass_angle_received": "Angle of the pass received.",
            "pass_direction_received_id": "Identifier for the direction of the pass received.",
            "pass_direction_received": "Description of the direction of the pass received.",
            "pass_distance_received": "Distance of the pass received.",
            "pass_range_received_id": "Identifier for the range of the pass received.",
            "pass_range_received": "Description of the range of the pass received.",
            "pass_outcome_id": "Identifier for the outcome of the pass.",
            "pass_outcome": "Description of the outcome of the pass.",
            "targeted_passing_option_event_id": "Identifier for the targeted passing option event.",
            "high_pass": "Whether the pass was a high pass.",
            "player_targeted_id": "Identifier for the targeted player.",
            "player_targeted_name": "Name of the targeted player.",
            "player_targeted_position_id": "Identifier for the position of the targeted player.",
            "player_targeted_position": "Position of the targeted player.",
            "player_targeted_x_pass": "X coordinate of the targeted player's pass.",
            "player_targeted_y_pass": "Y coordinate of the targeted player's pass.",
            "player_targeted_channel_pass_id": "Identifier for the channel of the targeted player's pass.",
            "player_targeted_channel_pass": "Description of the channel of the targeted player's pass.",
            "player_targeted_third_pass_id": "Identifier for the third pass of the targeted player.",
            "player_targeted_third_pass": "Description of the third pass of the targeted player.",
            "player_targeted_penalty_area_pass": "Whether the pass was in the penalty area of the targeted player.",
            "player_targeted_x_reception": "X coordinate of the targeted player's reception.",
            "player_targeted_y_reception": "Y coordinate of the targeted player's reception.",
            "player_targeted_channel_reception_id": "Identifier for the channel of the targeted player's reception.",
            "player_targeted_channel_reception": "Description of the channel of the targeted player's reception.",
            "player_targeted_third_reception_id": "Identifier for the third reception of the targeted player.",
            "player_targeted_third_reception": "Description of the third reception of the targeted player.",
            "player_targeted_penalty_area_reception": "Whether the reception was in the penalty area of the targeted player.",
            "player_targeted_distance_to_goal_start": "Distance to goal at the start for the targeted player.",
            "player_targeted_distance_to_goal_end": "Distance to goal at the end for the targeted player.",
            "player_targeted_angle_to_goal_start": "Angle to goal at the start for the targeted player.",
            "player_targeted_angle_to_goal_end": "Angle to goal at the end for the targeted player.",
            "player_targeted_average_speed": "Average speed of the targeted player.",
            "player_targeted_speed_avg_band_id": "Identifier for the average speed band of the targeted player.",
            "player_targeted_speed_avg_band": "Description of the average speed band of the targeted player.",
            "speed_difference": "Difference in speed.",
            "player_targeted_xpass_completion": "Completion status of the targeted player's pass.",
            "player_targeted_difficult_pass_target": "Whether the targeted player's pass was difficult.",
            "player_targeted_xthreat": "Related to the final pass attempted by the player in possession.  None if the player possession event did not end with a pass attempt or if we cannot determine who was the pass target.  Probability of a goal being scored in the next 10s after the pass was completed. Computed at the moment of the pass, whether the pass was completed or not.",
            "player_targeted_dangerous": "Whether the targeted player's pass was dangerous.",
            "n_passing_options": "Number of passing options available.",
            "n_off_ball_runs": "Number of off-ball runs.",
            "n_passing_options_line_break": "Number of passing options that break the defensive line.",
            "n_passing_options_first_line_break": "Number of passing options that break the first defensive line.",
            "n_passing_options_second_last_line_break": "Number of passing options that break the second last defensive line.",
            "n_passing_options_last_line_break": "Number of passing options that break the last defensive line.",
            "n_passing_options_ahead": "Number of passing options ahead.",
            "n_passing_options_dangerous_difficult": "Number of passing options that are both dangerous and difficult.",
            "n_passing_options_dangerous_not_difficult": "Number of passing options that are dangerous but not difficult.",
            "n_passing_options_not_dangerous_not_difficult": "Number of passing options that are neither dangerous nor difficult.",
            "n_passing_options_not_dangerous_difficult": "Number of passing options that are not dangerous but difficult.",
            "n_passing_options_at_start": "Number of passing options at the start.",
            "n_passing_options_at_end": "Number of passing options at the end.",
            "n_passing_options_ahead_at_start": "Number of passing options ahead at the start.",
            "n_passing_options_ahead_at_end": "Number of passing options ahead at the end.",
            "n_teammates_ahead_end": "Number of teammates ahead at the end.",
            "n_teammates_ahead_start": "Number of teammates ahead at the start.",
            "n_player_targeted_opponents_ahead_start": "Number of opponents ahead of the targeted player at the start.",
            "n_player_targeted_opponents_ahead_end": "Number of opponents ahead of the targeted player at the end.",
            "n_player_targeted_teammates_ahead_start": "Number of teammates ahead of the targeted player at the start.",
            "n_player_targeted_teammates_ahead_end": "Number of teammates ahead of the targeted player at the end.",
            "n_player_targeted_teammates_within_5m_start": "Number of teammates within 5 meters of the targeted player at the start.",
            "n_player_targeted_teammates_within_5m_end": "Number of teammates within 5 meters of the targeted player at the end.",
            "n_player_targeted_opponents_within_5m_start": "Number of opponents within 5 meters of the targeted player at the start.",
            "n_player_targeted_opponents_within_5m_end": "Number of opponents within 5 meters of the targeted player at the end.",
            "organised_defense": "Description of the organised defense.",
            "defensive_structure": "Description of the defensive structure.",
            "n_defensive_lines": "Number of defensive lines.",
            "first_line_break": "Description of the first line break.",
            "first_line_break_type_id": "None / 1 (Through) / 2 (Around)",
            "first_line_break_type": "None, if we know that a pass occurred but we are not able to have an accurate reception location.  None if it did not broke the first line, Around if it broke the line around. Through if it broke the line through.  If the player did not receive the ball, this value is predicted assuming the player had received the ball. ",
            "second_last_line_break": "Description of the second last line break.",
            "second_last_line_break_type_id": "Type ID of the second last line break.",
            "second_last_line_break_type": "Type of the second last line break.",
            "last_line_break": "Description of the last line break.",
            "last_line_break_type_id": "None / 1 (through) / 2 (around)",
            "last_line_break_type": "Type of the last line break.",
            "furthest_line_break_id": "ID of the furthest line break.",
            "furthest_line_break": "Description of the furthest line break.",
            "furthest_line_break_type_id": "Type ID of the furthest line break.",
            "furthest_line_break_type": "Type of the furthest line break.",
            "interplayer_distance": "Description of the interplayer distance.",
            "interplayer_distance_range_id": "ID of the interplayer distance range.",
            "interplayer_distance_range": "Range of the interplayer distance.",
            "interplayer_distance_start": "Start value of the interplayer distance.",
            "interplayer_distance_end": "End value of the interplayer distance.",
            "interplayer_distance_min": "Minimum interplayer distance.",
            "interplayer_distance_start_physical": "Physical start value of the interplayer distance.",
            "close_at_player_possession_start": "Description of close players at the start of player possession.",
            "interplayer_angle": "Description of the interplayer angle.",
            "interplayer_direction_id": "ID of the interplayer direction.",
            "interplayer_direction": "Direction of the interplayer.",
            "angle_of_engagement": "Angle of engagement.",
            "goal_side_start": "Goal side at the start.",
            "goal_side_end": "Goal side at the end.",
            "pass_distance": "Distance of the pass.",
            "pass_range_id": "ID of the pass range.",
            "pass_range": "Range of the pass.",
            "pass_angle": "Angle of the pass.",
            "pass_direction_id": "ID of the pass direction.",
            "pass_direction": "Direction of the pass.",
            "pass_ahead": "Description of whether the pass is ahead.",
            "n_opponents_ahead_player_in_possession_pass_moment": "Number of opponents ahead of the player in possession at the pass moment.",
            "n_opponents_ahead_pass_reception": "Number of opponents ahead at the pass reception.",
            "n_opponents_bypassed": "Number of opponents bypassed.",
            "location_to_player_in_possession_id_start": "Location ID relative to the player in possession at the start.",
            "location_to_player_in_possession_start": "Location relative to the player in possession at the start.",
            "location_to_player_in_possession_id_end": "Location ID relative to the player in possession at the end.",
            "location_to_player_in_possession_end": "Location relative to the player in possession at the end.",
            "distance_to_player_in_possession_start": "Distance to the player in possession at the start.",
            "distance_to_player_in_possession_end": "Distance to the player in possession at the end.",
            "player_in_possession_x_start": "X coordinate of the player in possession at the start.",
            "player_in_possession_y_start": "Y coordinate of the player in possession at the start.",
            "player_in_possession_channel_id_start": "Channel ID of the player in possession at the start.",
            "player_in_possession_channel_start": "Channel of the player in possession at the start.",
            "player_in_possession_third_id_start": "Third ID of the player in possession at the start.",
            "player_in_possession_third_start": "Third of the player in possession at the start.",
            "player_in_possession_penalty_area_start": "Penalty area status of the player in possession at the start.",
            "player_in_possession_x_end": "X coordinate of the player in possession at the end.",
            "player_in_possession_y_end": "Y coordinate of the player in possession at the end.",
            "player_in_possession_channel_id_end": "Channel ID of the player in possession at the end.",
            "player_in_possession_channel_end": "Channel of the player in possession at the end.",
            "player_in_possession_third_id_end": "Third ID of the player in possession at the end.",
            "player_in_possession_third_end": "Third of the player in possession at the end.",
            "player_in_possession_penalty_area_end": "Penalty area status of the player in possession at the end.",
            "targeted": "Indicates if the player was targeted.",
            "received": "Indicates if the pass was received.",
            "received_in_space": "Indicates if the pass was received in space.",
            "dangerous": "Indicates if the pass was dangerous.",
            "difficult_pass_target": "Indicates if the pass target was difficult.",
            "xthreat": "Expected threat value of the pass.",
            "xpass_completion": "Expected pass completion probability.",
            "passing_option_score": "Score of the passing option.",
            "predicted_passing_option": "Predicted passing option.",
            "peak_passing_option_frame": "Frame of the peak passing option.",
            "passing_option_at_player_possession_start": "Passing option at the start of player possession.",
            "n_simultaneous_runs": "Number of simultaneous runs.",
            "give_and_go": "Indicates if a give and go occurred.",
            "intended_run_behind": "Indicates if there was an intended run behind.",
            "push_defensive_line": "Indicates if the defensive line was pushed.",
            "break_defensive_line": "Indicates if the defensive line was broken.",
            "passing_option_at_start": "Passing option at the start.",
            "n_simultaneous_passing_options": "Number of simultaneous passing options.",
            "passing_option_at_pass_moment": "Passing option at the moment of the pass.",
            "n_opponents_ahead_end": "Number of opponents ahead at the end.",
            "n_opponents_ahead_start": "Number of opponents ahead at the start.",
            "n_opponents_overtaken": "Number of opponents overtaken.",
            "pressing_chain": "Pressing chain identifier.",
            "pressing_chain_length": "Length of the pressing chain.",
            "pressing_chain_end_type_id": "Identifier for the type of pressing chain end.",
            "pressing_chain_end_type": "Type of pressing chain end.",
            "pressing_chain_index": "Index within the pressing chain.",
            "index_in_pressing_chain": "Index position in the pressing chain.",
            "simultaneous_defensive_engagement_same_target": "Indicates simultaneous defensive engagement on the same target.",
            "simultaneous_defensive_engagement_same_target_rank": "Rank of simultaneous defensive engagement on the same target.",
            "affected_line_breaking_passing_option_id": "Identifier for the affected line breaking passing option.",
            "affected_line_break_id": "Identifier for the affected line break.",
            "affected_line_break": "Details of the affected line break.",
            "affected_line_breaking_passing_option_attempted": "Indicates if the affected line breaking passing option was attempted.",
            "affected_line_breaking_passing_option_xthreat": "Expected threat value of the affected line breaking passing option.",
            "affected_line_breaking_passing_option_dangerous": "Indicates if the affected line breaking passing option was dangerous.",
            "affected_line_breaking_passing_option_run_subtype_id": "Identifier for the run subtype of the affected line breaking passing option.",
            "affected_line_breaking_passing_option_run_subtype": "Run subtype of the affected line breaking passing option.",
            "possession_danger": "Indicates the danger level of the possession.",
            "beaten_by_possession": "Indicates if a player was beaten by possession.",
            "beaten_by_movement": "Indicates if a player was beaten by movement.",
            "stop_possession_danger": "Indicates if the possession danger was stopped.",
            "reduce_possession_danger": "Indicates if the possession danger was reduced.",
            "force_backward": "Indicates if a backward force was applied.",
            "xloss_player_possession_start": "Expected loss value at the start of player possession.",
            "xloss_player_possession_max": "Maximum expected loss value during player possession.",
            "xshot_player_possession_start": "Expected shot value at the start of player possession.",
            "xshot_player_possession_end": "Expected shot value at the end of player possession.",
            "xshot_player_possession_max": "Maximum expected shot value during player possession.",
            "is_player_possession_start_matched": "Indicates if the start of player possession was matched.",
            "is_player_possession_end_matched": "Indicates if the end of player possession was matched.",
            "is_previous_pass_matched": "Indicates if the previous pass was matched.",
            "is_pass_reception_matched": "Indicates if the pass reception was matched.",
            "fully_extrapolated": "Indicates if the data was fully extrapolated."
        }
    )

    rows = []
    for col in df.columns:
        desc = docs.get(col, "No description added yet – refer to SkillCorner documentation if needed.")
        rows.append({"column": col, "description": desc})

    return pd.DataFrame(rows)